/- @@@
Here's an assignment that you have a week to complete. You may do this on your own or in a group of up to three. If you do this work in a group, each group should have *one person* submit the results, and include a text note with the submission file explaining who participated and confirming that each participate was fully active in doing the work.

The goal of this assignment is to give you experience applying what you've learned, in the abstract, up until now, using a modern sastisfiability modulo theories (SMT) solver. You will show fluency formulating a specification using propositional logic with various theory extensions and demonstrate that you've "got it" by solving an interesting problem of your choice using Z3/Python.

Here's what to do. (1) There are many examples of Z3/Python solutions on the web, and available through generative AIs, and there are plenty of publicly available tutorials, as well. For example, you can easily find solutions for Sudoku online. Go learn to use Z3/Python on your own, by studying whatever tutorials, videos, etc., that you can find, along with concrete examples. I suggest that load examples into VSCode, run them, and really study them to see how they work and to see how problems you can understand informally can be formalized in this manner. (2) Pick a problem that is of interest to *you*, formalize the problem definition in Z3/Python, and show that you have produced a general purpose solver for problems of that kind. Studying a readily available solution for Sudoku would be a good start. You have succeeded when you known not only how to write the Python, but when you know that you've understood the kind of thinking processes needed to convert informal specifications of problems into formal definitions. It takes practice.

Submit your result (a self-contained Python program) along with a short report explaining (a) what problem you solved, (b) how you formalized a solution in Z3, and (c) how was your experience doing this work -- what was hard, easy, interesting, etc. It should be brief: at most a few paragraphs.
@@@ -/
